# -*- coding: utf-8 -*-
"""machine learng part 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gn9eJeX3bYfk4o_tiRHbhY_SzqT9gkv3

Part II: Time Series
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv("/content/drive/MyDrive/MonthWiseMarketArrivals_Clean.csv")
data.head()

data.info()

data1=data.loc[data.city=="MUMBAI"]
data1

data2=data1.drop(["month","year","quantity","priceMin","priceMax","state","city"],axis=1)
data2

data1.index=pd.PeriodIndex(data1.date,freq='M')
data1